name: Test

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo"cd ../"
      - run: echo"ls\n"
      - run: echo"cd ../\n"
      - run: echo"ls\n"
      - run: echo"python cheking.py\n"
