name: Test

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:   
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: jcdan3/devops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Hello World
        run: python ${{ env.DEVOPS_DIR }}/hello_world.py
      - run: python ${{ env.DEVOPS_DIR }}/cheking.py
