name: Test

on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: | 
              pip install pylint
              pip install pydocstyle
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
             pylint cheking.py
             pydocstyle cheking.py 
